WebFerreteria/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebFerreteria.Models;

namespace WebFerreteria.Controllers
{
    public class EmpresaController : Controller
    {
        private readonly FerreteriaDbContext _context;

        public EmpresaController(FerreteriaDbContext context)
        {
            _context = context;
        }

        // GET: Empresa
        public async Task<IActionResult> Index()
        {
            return View(await _context.Empresa.ToListAsync());
        }

        // GET: Empresa/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empresa = await _context.Empresa
                .FirstOrDefaultAsync(m => m.Id == id);
            if (empresa == null)
            {
                return NotFound();
            }

            return View(empresa);
        }

        // GET: Empresa/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Empresa/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Nit,Direccion,Telefono,Correo")] Empresa empresa)
        {
            if (ModelState.IsValid)
            {
                _context.Add(empresa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(empresa);
        }

        // GET: Empresa/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empresa = await _context.Empresa.FindAsync(id);
            if (empresa == null)
            {
                return NotFound();
            }
            return View(empresa);
        }

        // POST: Empresa/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Nit,Direccion,Telefono,Correo")] Empresa empresa)
        {
            if (id != empresa.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empresa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpresaExists(empresa.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(empresa);
        }

        // GET: Empresa/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empresa = await _context.Empresa
                .FirstOrDefaultAsync(m => m.Id == id);
            if (empresa == null)
            {
                return NotFound();
            }

            return View(empresa);
        }

        // POST: Empresa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var empresa = await _context.Empresa.FindAsync(id);
            if (empresa != null)
            {
                _context.Empresa.Remove(empresa);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpresaExists(int id)
        {
            return _context.Empresa.Any(e => e.Id == id);
        }
    }
}

WebFerreteria/Controllers/EntregaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebFerreteria.Models;

namespace WebFerreteria.Controllers
{
    public class EntregaController : Controller
    {
        private readonly FerreteriaDbContext _context;

        public EntregaController(FerreteriaDbContext context)
        {
            _context = context;
        }

        // GET: Entrega
        public async Task<IActionResult> Index()
        {
            var ferreteriaDbContext = _context.Entregas.Include(e => e.EntregadoPorNavigation).Include(e => e.Pedido).OrderBy(e => e.EntregadoPorNavigation.NombreCompleto);
            return View(await ferreteriaDbContext.ToListAsync());
        }

        // GET: Entrega/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entregas = await _context.Entregas
                .Include(e => e.EntregadoPorNavigation)
                .Include(e => e.Pedido)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (entregas == null)
            {
                return NotFound();
            }

            return View(entregas);
        }

        // GET: Entrega/Create
        public IActionResult Create()
        {
            ViewData["EntregadoPor"] = new SelectList(_context.Usuarios, "Id", "NombreCompleto");
            ViewData["PedidoId"] = new SelectList(_context.Pedidos, "Id", "Id");
            return View();
        }

        // POST: Entrega/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PedidoId,EntregadoPor,DireccionEntrega,FechaEntrega")] Entregas entregas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(entregas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EntregadoPor"] = new SelectList(_context.Usuarios, "Id", "NombreCompleto", entregas.EntregadoPor);
            ViewData["PedidoId"] = new SelectList(_context.Pedidos, "Id", "NombreCompleto", entregas.PedidoId);
            return View(entregas);
        }

        // GET: Entrega/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entregas = await _context.Entregas.FindAsync(id);
            if (entregas == null)
            {
                return NotFound();
            }
            ViewData["EntregadoPor"] = new SelectList(_context.Usuarios, "Id", "NombreCompleto", entregas.EntregadoPor);
            ViewData["PedidoId"] = new SelectList(_context.Pedidos, "Id", "Id", entregas.PedidoId);
            return View(entregas);
        }

        // POST: Entrega/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PedidoId,EntregadoPor,DireccionEntrega,FechaEntrega")] Entregas entregas)
        {
            if (id != entregas.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(entregas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EntregasExists(entregas.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EntregadoPor"] = new SelectList(_context.Usuarios, "Id", "Id", entregas.EntregadoPor);
            ViewData["PedidoId"] = new SelectList(_context.Pedidos, "Id", "Id", entregas.PedidoId);
            return View(entregas);
        }

        // GET: Entrega/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entregas = await _context.Entregas
                .Include(e => e.EntregadoPorNavigation)
                .Include(e => e.Pedido)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (entregas == null)
            {
                return NotFound();
            }

            return View(entregas);
        }

        // POST: Entrega/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var entregas = await _context.Entregas.FindAsync(id);
            if (entregas != null)
            {
                _context.Entregas.Remove(entregas);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EntregasExists(int id)
        {
            return _context.Entregas.Any(e => e.Id == id);
        }
    }
}

WebFerreteria/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebFerreteria.Models;

namespace WebFerreteria.Controllers
{
    public class PedidoController : Controller
    {
        private readonly FerreteriaDbContext _context;

        public PedidoController(FerreteriaDbContext context)
        {
            _context = context;
        }

        // GET: Pedido
        public async Task<IActionResult> Index(string estado)
        {
            // Obtener todos los estados distintos para el dropdown
            var estados = await _context.Pedidos
                .Select(p => p.Estado)
                .Distinct()
                .ToListAsync();

            ViewData["Estados"] = estados;
            ViewData["EstadoSeleccionado"] = estado;

            // Consulta base
            var query = _context.Pedidos
                .Include(p => p.Cliente)
                .AsQueryable();

            // Aplicar filtro si se seleccionó un estado
            if (!string.IsNullOrEmpty(estado))
            {
                query = query.Where(p => p.Estado == estado);
            }

            // Ordenar y ejecutar la consulta
            var pedidos = await query
                .OrderBy(p => p.Cliente.Nombre)
                .ToListAsync();

            return View(pedidos);
        }

        // GET: Pedido/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedidos = await _context.Pedidos
                .Include(p => p.Cliente)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pedidos == null)
            {
                return NotFound();
            }

            return View(pedidos);
        }

        // GET: Pedido/Create
        public IActionResult Create()
        {
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Nombre");
            return View();
        }

        // POST: Pedido/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ClienteId,Fecha,Estado")] Pedidos pedidos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pedidos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Nombre", pedidos.ClienteId);
            return View(pedidos);
        }

        // GET: Pedido/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedidos = await _context.Pedidos.FindAsync(id);
            if (pedidos == null)
            {
                return NotFound();
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Nombre", pedidos.ClienteId);
            return View(pedidos);
        }

        // POST: Pedido/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ClienteId,Fecha,Estado")] Pedidos pedidos)
        {
            if (id != pedidos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedidos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidosExists(pedidos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Nombre", pedidos.ClienteId);
            return View(pedidos);
        }

        // GET: Pedido/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedidos = await _context.Pedidos
                .Include(p => p.Cliente)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pedidos == null)
            {
                return NotFound();
            }

            return View(pedidos);
        }

        // POST: Pedido/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pedidos = await _context.Pedidos.FindAsync(id);
            if (pedidos != null)
            {
                _context.Pedidos.Remove(pedidos);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PedidosExists(int id)
        {
            return _context.Pedidos.Any(e => e.Id == id);
        }
    }
}

WebFerreteria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es" data-theme="light">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - La Puntilla</title>

    <!-- Materialize CSS -->
    <link rel="stylesheet" href="~/materialize/css/materialize.min.css" />

    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

    <!-- Estilos personalizados -->
    <link rel="stylesheet" href="~/css/theme_style.css" asp-append-version="true" />
</head>

<body>
    <header>
        <ul id="slide-out" class="sidenav sidenav-fixed grey lighten-4">
            <li><a class="brand-logo center blue-text text-darken-3" style="padding: 10px;">La Puntilla</a></li>
            <li><a asp-controller="Home" asp-action="Index"><i class="material-icons">home</i>Home</a></li>
            <li><a asp-controller="Home" asp-action="Privacy"><i class="material-icons">security</i>Privacidad</a></li>
            <li><a asp-controller="Usuario" asp-action="Index"><i class="material-icons">person</i>Usuarios</a></li>
            <li><a asp-controller="Clientes" asp-action="Index"><i class="material-icons">group</i>Clientes</a></li>
            <li><a asp-controller="Empresa" asp-action="Index"><i class="material-icons">business</i>Empresa</a></li>
            <li><a asp-controller="Entrega" asp-action="Index"><i class="material-icons">local_shipping</i>Entrega</a></li>
            <li><a asp-controller="Producto" asp-action="Index"><i class="material-icons">shopping_cart</i>Producto</a></li>
            <li><a asp-controller="Pedido" asp-action="Index"><i class="material-icons">assignment</i>Pedido</a></li>
            <li><a asp-controller="DetallePedido" asp-action="Index"><i class="material-icons">list</i>Detalle Pedido</a></li>
            <li><a asp-controller="Factura" asp-action="Index"><i class="material-icons">receipt</i>Factura</a></li>
        </ul>

        <nav class="blue darken-2">
            <div class="nav-wrapper">
                <a href="#" data-target="slide-out" class="sidenav-trigger left show-on-large"><i class="material-icons">menu</i></a>
                <ul class="right">
                    <li>
                        <a href="#" id="themeToggle">
                            <i class="material-icons">brightness_6</i>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <main class="container" style="margin-left: 300px;">
        @RenderBody()
    </main>

    <footer class="page-footer grey lighten-4" style="margin-left: 300px;">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <p class="grey-text text-darken-1">
                        &copy; @DateTime.Now.Year - WebFerreteria -
                        <a asp-controller="Home" asp-action="Privacy">Privacidad</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="~/materialize/js/materialize.min.js"></script>
    <script src="~/js/mis_scripts.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            M.AutoInit();

            const toggle = document.getElementById('themeToggle');
            const htmlEl = document.documentElement;

            // Cargar tema desde localStorage
            const savedTheme = localStorage.getItem('theme');
            if (savedTheme) htmlEl.setAttribute('data-theme', savedTheme);

            toggle.addEventListener('click', function () {
                let current = htmlEl.getAttribute('data-theme');
                let next = current === 'dark' ? 'light' : 'dark';
                htmlEl.setAttribute('data-theme', next);
                localStorage.setItem('theme', next);
            });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>